### ISSUE TITLE
Problem with accessing  MFi Device..

### ISSUE THREAD

**Issue by sakaatavion** [jeradesign/GameControllerTest#1]
How to access MFi Device through iOS Application.

Thanks.....

Any help would be appreciated....

**Comment by jeradesign** [comment]
If you're a hardware developer, you use the external accessory framework after signing an agreement with Apple.

If you're a 3rd party developer, you use the API provided by the hardware developer (e.g. Pebble, Motrr Galileo, Romotive Romo) and then get hardware developer to whitelist your app for approval in the app store.

MFi game controllers are a special case.  All MFi game controllers conform to a special API provided by Apple.  Any code you write to that API works on any MFi game controller.

None of this applies to devices talking to iOS via Bluetooth LE.  You don't need a special MFi agreement with Apple.  Your apps go through the standard app approval process.
